### ISSUE TITLE
Confirm event results in testing

### ISSUE THREAD

**Issue by dapp-whisperer** [Citadel-DAO/citadel-contracts#113]
To ensure the appropriate data is emitted

**Comment by sajanrajdev** [comment]
In general, events checking should be integrated to all test flows, specially for those events used to index accounting changes to the API. The following can be used as a reference: https://github.com/Citadel-DAO/citadel-contracts/blob/b33132b9471ae1f2fd6e7c27e88e46a46a679133/src/test/Vesting.t.sol#L53-L60

**Comment by sajanrajdev** [comment]
Done
