### ISSUE TITLE
Move Locker back to RewardsDuration = 1 day

### ISSUE THREAD

**Issue by dapp-whisperer** [Citadel-DAO/citadel-contracts#117]
* Update on [locker](https://github.com/Citadel-DAO/staked-citadel-locker/blob/main/src/StakedCitadelLocker.sol) here
* Update artifact in this repo

**Comment by shinji2048** [comment]
https://github.com/Citadel-DAO/staked-citadel-locker/pull/6
Update to citadel locker contract
