### ISSUE TITLE
Adapt Locking tests to check new `cumulativeDistributed` tracking

### ISSUE THREAD

**Issue by sajanrajdev** [Citadel-DAO/citadel-contracts#132]
Test the feature introduced by: https://github.com/Citadel-DAO/staked-citadel-locker/commit/8925bd62c12f7bf2bcd59753d21550cd6ad496f7

Also, test that `cumulativeClaimed` also updates correctly.

**Comment by Fatimanaz** [comment]
https://github.com/Citadel-DAO/citadel-contracts/pull/152
