### ISSUE TITLE
Test `daoComittments` and multiple simultaneous KnightingRounds flow

### ISSUE THREAD

**Issue by sajanrajdev** [Citadel-DAO/citadel-contracts#133]
- Test that `daoCommitments` are registered properly along the flows. The distribution to the DAOs will be decided upon this parameter so it is important to keep good track of it.
- Integration test with multiple KnightingRound contracts, each contract with a different `_tokenIn` but the rest of the parameters being the same. This will be closer to what will happen in reality, a user, “whitelisted” will be able to buy on the round with multiple assets. This user can also vote for different DAOs using the different contracts, that’s why the daoCommitments will be a better indicator vote distribution. Also, `sale` events should be tracked and the amounts of `tokenOutAmount_` by `_daoId` should match those of the daoCommitments.

**Comment by dapp-whisperer** [comment]
great test - I'd also do a confirmation of results with the same user buying multiple times on a single KnightingRound
