### ISSUE TITLE
Create local deploy script with all mocks

### ISSUE THREAD

**Issue by mrbasado** [Citadel-DAO/citadel-contracts#147]
Create a script to deploy everything locally.
Should do everything deploy-local.ts does (make ctdl, xctdl, locker, staker, funding, kngihtround, vlCTDL, unlocked rewards, etc) but instead of having a mainnet fork all the erc20s used in the knighting rounds will be mocked and given to signers[0]. for example: CVX, bveCVX, renBTC, WBTC, WETH, USDC, etc.

**Comment by dapp-whisperer** [comment]
A few things to keep in mind from our conversation:

- Confirm the decimal situation for wBTC KnightingRound contract works as expected
- Have realistic prices for each Knighting Round contract

- Setup oracles for each Funding contract, and ensure they have realistic price values
( the oracles can be EOAs for now)

**Comment by dapp-whisperer** [comment]
Ensure the proper root is set for KR guestList
```
const guestListRoot =
    "0x8916c3fedd925241fcbba35af8d2380b5658ad8fa17e1b525bb1851107a36b35";

  await knightingRoundGuestList.connect(techOps).setGuestRoot(guestListRoot);
```

**Comment by aj-maz** [comment]
@dapp-whisperer I think it's done and we should close this
