### ISSUE TITLE
Add tests for the Funding registry/factory

### ISSUE THREAD

**Issue by sajanrajdev** [Citadel-DAO/citadel-contracts#181]
A new Funding registry/factory was [written](https://github.com/Citadel-DAO/citadel-contracts/pull/179) in a similar fashion that the KRs Registry. Tests should be written to ensure that:
- The factory operations work as expected
- Funding rounds generated from the factory work as expected
- The registry works as expected

**Comment by aj-maz** [comment]
Should be since #179 has resolved it.
