### ISSUE TITLE
Unusued withdrawal fees

### ISSUE THREAD

**Issue by GalloDaSballo** [Citadel-DAO/citadel-contracts#22]
https://github.com/Citadel-DAO/citadel-contracts/blob/8f54330d745ab48e25b3c0c0822d975b407bffcd/src/StakedCitadel.sol#L838

If you don't plan on having them, delete this line + the math above to save thousands of gas

**Comment by dapp-whisperer** [comment]
keeping this for now to avoid making changes and keep the options open. slated for potential removal down the line
