### ISSUE TITLE
Send test user required assets in forknet deploy sript

### ISSUE THREAD

**Issue by dapp-whisperer** [Citadel-DAO/citadel-contracts#24]
The current [forknet deploy script](https://github.com/Citadel-DAO/citadel-contracts/blob/main/scripts/deploy-local.js) does not send the assets used in funding to the test user.

# The Task
Mint or force CVX and wBTC to the test user, which is signers[0]

You can reference BaseFixture.sol for a solidity version of forcing assets to the test users.

**Comment by anonachan** [comment]
hi, i just made an PR to this issue:
https://github.com/Citadel-DAO/citadel-contracts/pull/35

but i wasn't sure how much token is needed so i just made up some arbitrary amounts

**Comment by dapp-whisperer** [comment]
arbitrary amounts sound good, merged
