### ISSUE TITLE
Staked Citadel success paths

### ISSUE THREAD

**Issue by dapp-whisperer** [Citadel-DAO/citadel-contracts#37]
Story: Users should be able to stake and unstake citadel

Confirm the simple case of users staking & unstaking citadel

- user has citadel
- they stake it and relevant varialbes change
- they unstake it and the tokens go to the vester. The appropriate vesting data is added.
- the user is able to withdraw the appropriate level of vesting coins as time advances

**Comment by Fatimanaz** [comment]
PR Link- https://github.com/Citadel-DAO/citadel-contracts/pull/41
