### ISSUE TITLE
Production Knighting Round - Forknet Setup

### ISSUE THREAD

**Issue by dapp-whisperer** [Citadel-DAO/citadel-contracts#39]
The Knighting Round will occur in two phases, each lasting 3 days. The details are described in the phases below.
As the Knighting Round parameters have matured, we need a test suite setup and deploy script for them.  

Task: 
* Create a variant of the [forknet deploy script](https://github.com/Citadel-DAO/citadel-contracts/blob/main/scripts/deploy-local-fresh.js) in Hardhat that adds the deployment of the following setup.

## Phase 1: Primary Asset Acquisition
Deploy a KnightingRound contract for each of the following assets:
- wBTC
- renBTC
- ibBTC badger vault token
- WETH
- FRAX
- USDC

The saleDuration should be 3 days.

The price of each asset should correspond to $21 per citadel, using rough market prices for each asset at the current time for realism. There is no cap per asset in this phase.

Deploy a single [guestlist](https://github.com/Citadel-DAO/citadel-contracts/blob/main/src/KnightingRoundGuestlist.sol) for use in each KnightingRound contract.
* guestlist root is `0x7e5eaba80a7bd7636e9edd5c7a84daa71b476e698bb85f06202152751fb9b5f8 ` 
* assign this guestList as the guestList for each KnightingRound contract.
  
## Phase 2: Yield Influence Asset Acquisition
Right after the first round finishes, the second round should start.

Deploy a KnightingRound contract for each of the following assets:
- Badger
- CVX 
- bveCvx

The saleDuration for these should be 2 days.

No guestlist is needed for each contract in this round.

The price of each asset should correspond to $25 per citadel, using rough market prices for each asset at the current time for realism.
Capped sale: setTokenInLimit() should be used to cap the sale to aprox. $1m woth of the asset in question

**Comment by ICEBADGER** [comment]
@Ajand  can you set the "Projected Ship Date" for when you aim to be completed ?

**Comment by aj-maz** [comment]
> 

Sorry I didn't see it. It's ready for review.
