### ISSUE TITLE
Deploy script for new contract repo in hardhat

### ISSUE THREAD

**Issue by dapp-whisperer** [Citadel-DAO/citadel-contracts#4]
The previous iteration of the contract repo used [brownie](https://eth-brownie.readthedocs.io/) for testing and deployment. We're now using Foundry for the testing suite for the [massive performance gains](https://www.paradigm.xyz/2021/12/introducing-the-foundry-ethereum-development-toolbox) and ability to write tests in solidity.

You can see the existing deploy script [here](https://github.com/Citadel-DAO/citadel-contracts-draft/blob/main/scripts/test_deploy.py).

## Why switch to Hardhat?
The web2 team reports that the hardhat ganache variant is more reliable than ganache itself for UI testing
In addition, verification of deployed contracts seems to be reliable from Hardhat and this is not the case from brownie in our experience.

## Expected issues
Handling dependencies, and the contract directory setup.
Foundry does have a way to handle things like hardhat, and hardhat may be flexible as well.
<img width="712" alt="image" src="https://user-images.githubusercontent.com/69157701/161584199-01218d83-3b62-4d0d-b818-eab2a527a564.png">
[link](https://book.getfoundry.sh/projects/dependencies.html)

**Comment by yongkangc** [comment]
@dapp-whisperer I was wondering if the team wants to switch to foundry+hardhat or completely to hardhat?

cc @MadroneXBT

**Comment by legacy** [comment]
Yeah I was wondering about the same thing

**Comment by dapp-whisperer** [comment]
foundry+hardhat.

people prefer foundry for testing but it doesn't easily handle deploy + verification scripts that hardhat does gracefully.

**Comment by aj-maz** [comment]
I'm working on this and I have done some research and it appeared that currently, hardhat does not support remappings.
I'm changing imports of contracts to accomplish this compatibility.
