### ISSUE TITLE
Claiming fails for a certain time when a user has an existing `claimed` amount

### ISSUE THREAD

**Issue by sajanrajdev** [Citadel-DAO/citadel-contracts#47]
This issue related to the `StakedCitadelVester.sol` contract:
![image](https://user-images.githubusercontent.com/25463788/163870834-e9e237bb-da7a-4c40-b625-93a84019873f.png)

This issue can be replicated by running the following test: https://github.com/Citadel-DAO/citadel-contracts/blob/a0a2d1cef64102be473b74e5fa60ffd92ad88450/src/test/Vesting.t.sol#L229-L287

A solution would be to keep accounting of different vesting periods for the same user separately.

**Comment by harleythedogC4** [comment]
I put in a PR to fix this issue a few days ago: https://github.com/Citadel-DAO/citadel-contracts/pull/44

**Comment by sajanrajdev** [comment]
Fixed with PR #44
