### ISSUE TITLE
Test new Locker access control paradigm

### ISSUE THREAD

**Issue by dapp-whisperer** [Citadel-DAO/citadel-contracts#81]
(Flagging for myself in the future)

Locker now uses GAC ACL, tests should be modified to reflect this.

**Comment by sajanrajdev** [comment]
Locker GAC Roles ACL is only partially tested within some of the flows n this repo. Three functions check for reverts on GAC permissions when there are 8 permissioned functions in the contract.

@Fatimanaz, we should extract permissions test for the locker into a centralized location as we did for the rest of the contracts. In this case, I suggest that we do it wihtin the staked-citadel-locker repo for better change/testing flow resilience. You can add Roles test to the [GlobalAccessControl.t.sol](https://github.com/Citadel-DAO/staked-citadel-locker/blob/main/src/test/GlobalAccessControl.t.sol) test suite like you did in this repo.

**Comment by sajanrajdev** [comment]
Tackled through: https://github.com/Citadel-DAO/staked-citadel-locker/pull/9/files
