### ISSUE TITLE
Function claim() in StakedCitadelVester.sol not protected when protocol in pause mode 

### ISSUE THREAD

**Issue by dapp-whisperer** [Citadel-DAO/citadel-contracts#84]
See [PR](https://github.com/Citadel-DAO/citadel-contracts/pull/91)
* All write functions on Vester are gacPausable, this functionality should be tested
* claim is in addition nonReentrant

**Comment by dapp-whisperer** [comment]
@sajanrajdev passing this over to you as testing lead - just indicating it's in that stage of the process

**Comment by sajanrajdev** [comment]
Pausing tests were added: https://github.com/Citadel-DAO/citadel-contracts/pull/91/commits/2f19ae79ef5d71554ba82cc5e390a7d2725302ca
