### ISSUE TITLE
Fix Locker's unlocking and kicking periods

### ISSUE THREAD

**Issue by sajanrajdev** [Citadel-DAO/citadel-contracts#97]
As the `rewardsDuration` variable of the locker was changed to 21 days, two other things changes on the unlocking behavior unintentionally:
- The time it takes a user to unlock their assets after the first time they lock now takes 21 weeks + 21 days (used to be +1 day): https://github.com/Citadel-DAO/staked-citadel-locker/blob/3305751ee05edf306b87abced7318d85f817b3e3/src/StakedCitadelLocker.sol#L729-L731
- Also, the rewards kicking delay is equal to rewardsDuration times a multiplier (kickRewardEpochDelay, default 4). This means that now, kickers have to wait 4*21 days to be able to kick rewards, and idle assets can stay sitting on the contract for that long: https://github.com/Citadel-DAO/staked-citadel-locker/blob/3305751ee05edf306b87abced7318d85f817b3e3/src/StakedCitadelLocker.sol#L961

These extended wait times are undesired and seem to be the result of the original designers reusing the `rewardsDuration` as a 1 day constant, which, now changed to 21 altered the result. Adaptations should be made and tested to return the wait times to the orginal values while ensuring the correct behavior of the locking cycle.

**Comment by sajanrajdev** [comment]
Note: The following tests from the Locking.t.sol test suite were commented out as they currently fail for this reason (and CI was broken): 
![image](https://user-images.githubusercontent.com/25463788/165977067-6e857dcb-7ed7-4444-858a-4146a8b0b440.png)

Adapting them could have lead to passing undesired behavior. The tests should be reactivated when the issue is fixed.

**Comment by brianendo** [comment]
Would it make sense to create a new variable like `unlockDuration` and set that at 1 day then just use it in those two instances?

**Comment by sajanrajdev** [comment]
I think that's the way to go, this certainly works for he kicking issue. Unfortunately, applying this to the issue with the "first lock duration" breaks on integration. I will investigate further, working on some tests on the Locker's repo to debug.

**Comment by brianendo** [comment]
I tried adding the `unlockDuration` for 1 day and it fixed the `testRelocking` and `testUnlockAndReward` tests but weirdly ran into issues with `testKickRewards`.

<img width="621" alt="Screen Shot 2022-04-29 at 2 15 20 PM" src="https://user-images.githubusercontent.com/7454457/166070149-ea76087c-116a-4e48-bf12-a6c14bd7186b.png">

**Comment by brianendo** [comment]
The issue is that we are using a new `_checkDelay` that is different than the `rewardsDuration`. I think this is altering the currentEpoch calculation below which messes up the reward. 

https://github.com/Citadel-DAO/staked-citadel-locker/blob/3305751ee05edf306b87abced7318d85f817b3e3/src/StakedCitadelLocker.sol#L838-L854

**Comment by dapp-whisperer** [comment]
In light of the complexities and unknowns of pursuing this path, we're going to move back to rewardsDuration = 1 day for now and re-evaluate this in the future

**Comment by dapp-whisperer** [comment]
@brianendo see [this issue](https://github.com/Citadel-DAO/citadel-contracts/issues/117) if you want to work on moving things back

**Comment by sajanrajdev** [comment]
rewardsDuration change was reverted and, hence, this issue is now irrelevant. Tests have been uncommented and they all pass now. Closing.
